### ISSUE TITLE
Progress Report

### ISSUE THREAD

**Issue by Naetw** [Naetw/A-simple-ray-tracer#1]
Hi, @yungyuc

Here are my progress report and some stuff I'd like to share. It would be great if I can hear some advices from you! Thanks in advance!

---

Μy schedule:

- [x] Week 7 (10/26)
    - Decide how much I'm going to extend my ray tracer (includes the second book?). The following schedule may change a lot according this decision. For now, It's based on the content of the first book
    - Decide the testing framework for private APIs
- [x] Week 8 (11/2) (finished @ 11/07)
    - Implement the first three class (`Point3`, `Color`, `Ray`) and corresponding unit tests
- [x] Week 9 (11/9) (hw4) (finished @ 11/18) 
    - Implement class `Hittable`, `Sphere` and corresponding unit tests
- [x] Week 10 (11/16) (finished @ 11/24)
    - Implement class `HittableList` and corresponding unit tests
- [ ] Week 11 (11/23) (hw5)
    - Implement class `Camera` and corresponding unit tests
    - Implement class `Material` and corresponding unit tests (if available)
- [ ] Week 12 (11/30)
    - Implement class `Material` and corresponding unit tests
- [ ] Week 13 (12/7) (hw6)
    - Handle some detailed physics attributes which have not been mentioned above
- [ ] Week 14 (12/14)
    - Handle some detailed physics attributes which have not been mentioned above (cont)
    - Finalize the public APIs
- [ ] Week 15 (12/21)
    - Prepare slides for presentation

As the actual finished date listed above, I'm a bit behind in this schedule because I have 0 progress in week 9. In week 10 & 11, I have tried to catch up but I'm not confident of achieving it. 

---

Let's share something interesting that I met during the development.

## 1. Annoying design choice

What I'm developing is a ray tracer which needs to simulate the situation that a ray hits an object and then compute the pixel color based on the normal vector on the intersection point. In the [tutorial](https://raytracing.github.io/books/RayTracingInOneWeekend.html), the author designed this using just **one** function - `hit`:

```cpp
bool hit(const ray& r, double t_min, double t_max, hit_record& rec) const;
```

which is a bit nasty to me since`hit` function takes a reference to `hit_record` as an argument and it stores information (hit point, normal vector, etc.) about the hit point in that `hit_record` object.

I thought it does too many things in just one function so I tried to separate it into a few functions at first:

```cpp
bool hit(const ray& r);

Point3 getHitPoint(const Ray &ray, double t_min, double t_max);

Vector3 getNormalVector(const Point3 &intersection_point, const Ray &ray);

// A ray is in the form of A (origin) + t * b (direction vector) which means a ray can be extended based on factor "t"
double getFactorT(const Ray &ray, double t_min, double t_max);
```

However, the lower 3 functions are highly correlated. They all share some common calculations to get the result. I was thinking of adding some overloaded version of them to reuse the result of calculation. Then I realized that this would lead to exposing too much details about the implementation which should not be concerned by the user.

After being torn between having a function that writes in some arguments and having functions that do just one simple thing but with performance penalty, I finally design it like this:

```cpp
bool hit(const Ray& ray);

HitRecord getHitRecord(const Ray &ray, double t_min, double t_max);
```

Although functions `hit` and `getHitRecord` still have some common calculation, I take that as the trade-off.

## 2. An interesting experience on writing unit tests

When I tried to wrap up the work of week 10, I found that the image my ray tracer generated is different to the one in tutorial. After debugging, I found that my unit tests didn't help me catch this stinky bug!

Before talking about the bug, I need to introduce some background.

To determine whether a ray hits a sphere is quite straightforward. A sphere is in the form of `x^2 + y^2 + z^2 = R^2` and a ray can be extended to a point in the form of `A + tb`, where `A` is the origin of the ray and `b` is the direction. So what I need to do is applying the result of `A + tb` - `(x, y, z)` in the formula of sphere with assuming the center of the sphere is at `(𝐶𝑥,𝐶𝑦,𝐶𝑧)`:

```
(𝑥−𝐶𝑥)^2+(𝑦−𝐶𝑦)^2+(𝑧−𝐶𝑧)^2=𝑟^2
```

Actually, it's much easier to calculate the result if I replace (x, y, z) with `A + tb`:

```
(𝐀+𝑡𝐛−𝐂)⋅(𝐀+𝑡𝐛−𝐂)=𝑟^2

...

𝑡^2 * 𝐛⋅𝐛 + 2𝑡 * 𝐛⋅(𝐀−𝐂) + (𝐀−𝐂)⋅(𝐀−𝐂) − 𝑟^2=0
```

where `A`, `b`, `C`, `r` are all constant. It can be viewed as a quadratic equation. Then, we can determine the hit by using discriminant and the hit point can be solved by using quadratic formula for the roots.

![](https://github.com/RayTracing/raytracing.github.io/blob/master/images/fig-1.04-ray-sphere.jpg?raw=true)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Quadratic_formula.svg/220px-Quadratic_formula.svg.png)

So, the code for the quadratic formula is like:

```cpp
auto root = (-factors.b - sqrt_discriminant) / (2 * factors.a);
```

BUT, I wrote it carelessly in:

```cpp
auto root = (-factors.b - sqrt_discriminant) / 2 * factors.a;
```

which computes the wrong result of the root.

And, even though I have written a unit test for function `getHitRecord`, it doesn't catch this bug since I use a really simple value for the ray. The `factors.a` in that situation is **`1`** which won't be a problem when there's no parenthesis.

I have learned that even though using simple data is easy to calculate the right answer by hand, it's too lazy and simple to cover the functionality. Next time, I should avoid using something like `1` in unit test, use more test cases or use an actual case in unit tests.

**Comment by yungyuc** [comment]
For the ray hitting algorithm, I am guessing that you probably have tried to move both functions to a class, like:

```cpp
struct Hitter
{

bool hit(const Ray & ray);
HitRecord getHitRecord(const Ray &ray, double t_min, double t_max);

// common data.

};
```

This pattern may work when both functions share common intermediate data, which is an assumption may or may not apply in your code.

I am not sure whether or not the original one-function implementation took the performance into account.  It's a reasonable approach if it did.

**Comment by yungyuc** [comment]
I concur with you that test data need to incorporate non-triviality.  Specifically, we need to include values other than 0 and 1!

**Comment by Naetw** [comment]
> I am guessing that you probably have tried to move both functions to a class

Yeah, I have an abstract class `Hittable` that declares two virtual function `hit` and `getHitRecord`. Derived classes can be any object that is hittable and they should implement these two function on their own based on their attributes.

I had the same idea (sharing common intermediate data) before, but I found that in this way, I have to bind these two functions together. That is, I have to make the user have the constraint that these two functions should be always used together, otherwise, it may return the result of other rays. (Or I have to maintain a state that records which ray the current intermediate data belong to)

Therefore, I chose to sacrifice some performance for simpler & harder to be misused design.

> I am not sure whether or not the original one-function implementation took the performance into account. It's a reasonable approach if it did.

The author didn't mention the performance, but he did mention that he preferred to use simpler language feature instead of some magic so that he can convey the concepts of ray tracer easier and clearer. So I thought the original one-function implementation is just for making the tutorial as simple as possible.

**Comment by yungyuc** [comment]
> > I am guessing that you probably have tried to move both functions to a class
> 
> Yeah, I have an abstract class `Hittable` that declares two virtual function `hit` and `getHitRecord`. Derived classes can be any object that is hittable and they should implement these two function on their own based on their attributes.
> 
> I had the same idea (sharing common intermediate data) before, but I found that in this way, I have to bind these two functions together. That is, I have to make the user have the constraint that these two functions should be always used together, otherwise, it may return the result of other rays. (Or I have to maintain a state that records which ray the current intermediate data belong to)
> 
> Therefore, I chose to sacrifice some performance for simpler & harder to be misused design.
> 

It will be informative to profile the performance.  At this point it looks OK to keep simple interface.  If you later choose to change the implementation, inlining should avoid runtime overhead.

> > I am not sure whether or not the original one-function implementation took the performance into account. It's a reasonable approach if it did.
> 
> The author didn't mention the performance, but he did mention that he preferred to use simpler language feature instead of some magic so that he can convey the concepts of ray tracer easier and clearer. So I thought the original one-function implementation is just for making the tutorial as simple as possible.

In this case, it's a good practice to extend the implementation using 'more complex language features'.  You may do it in a later phase of the project.

**Comment by Naetw** [comment]
> In this case, it's a good practice to extend the implementation using 'more complex language features'. You may do it in a later phase of the project.

Sure!!!

---

Thanks for your reply!
